# All clients from InvoiceOcean (auto-generated from fmcgoods-clients.xls)

CLIENTS = {
    'A.A.W. VAN GESTEL NL': {
        "vat_id":    '',
        "street":    '',
        "postcode":  '',
        "city":      '',
        "country":   '',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '203700672',
    },
    'Arrow Logistics & Services, SIA': {
        "vat_id":    'LV40103378981',
        "street":    'Semulinu 8-1',
        "postcode":  'LV-1045',
        "city":      'Riga',
        "country":   'Latvia',
        "email":     'info@arrows.lv',
        "phone":     '',
        "invoiceocean_id": '160887546',
    },
    'Brandshandel Limited Liability Company': {
        "vat_id":    '193674952',
        "street":    'Damashevski zavulak, 11 “A”, room 712',
        "postcode":  '220036',
        "city":      'Minsk',
        "country":   'Belarus',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '225997324',
    },
    'Casovnikova Liudmila': {
        "vat_id":    '',
        "street":    '',
        "postcode":  '',
        "city":      '',
        "country":   'France',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '211697550',
    },
    'Casus Belli Advocats S.L.': {
        "vat_id":    'B56347883',
        "street":    'Calle Capitán Dema 36 40B',
        "postcode":  '03007',
        "city":      'Alicante',
        "country":   '',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '239382756',
    },
    'Chasovnikov Vladimir': {
        "vat_id":    '444 486 252 00018',
        "street":    'Du Pylone',
        "postcode":  '06600',
        "city":      'Antibes',
        "country":   'France',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '160942115',
    },
    'Chic & Basic 2010 S.L.': {
        "vat_id":    'B65316093',
        "street":    'Calle Castillejos 205',
        "postcode":  '08013',
        "city":      'Barcelona',
        "country":   'Spain',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '164882952',
    },
    'Daniil Kac': {
        "vat_id":    '',
        "street":    'M.Mažvydo g.4',
        "postcode":  '06277',
        "city":      'Vilnius',
        "country":   'Lithuania',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '199381243',
    },
    'EESTI KAUBANDUS-TOOSTUSKODA MTU': {
        "vat_id":    'EE100559448',
        "street":    'stonian Chamber of Commerce and Industry, Toom-Kooli 17',
        "postcode":  '10130',
        "city":      'Tallinn',
        "country":   'Estonia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '203701341',
    },
    'Fakturownia Sp. z o.o.': {
        "vat_id":    'PL5213704420',
        "street":    'Juliana Smulikowskiego 6/8',
        "postcode":  '00-389',
        "city":      'Warszawa',
        "country":   'Poland',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '161186973',
    },
    'GFC DON PAPA SP Z O O': {
        "vat_id":    '9662170384',
        "street":    'Warszawska 20, lok. 11',
        "postcode":  '15-063',
        "city":      'Warsaw',
        "country":   'Poland',
        "email":     'purchase@vipcorptrade.com',
        "phone":     '',
        "invoiceocean_id": '196941101',
    },
    'Kregerlorna, UAB': {
        "vat_id":    '155985491',
        "street":    'Vilties g. 4-23',
        "postcode":  '31118',
        "city":      'Visaginas',
        "country":   '',
        "email":     'kregerlorna@gmail.com',
        "phone":     '',
        "invoiceocean_id": '202234804',
    },
    'Limited liability company "Center Logistic"': {
        "vat_id":    '7724403494',
        "street":    'Zolotorozhsky lane MS house 13, office 9',
        "postcode":  '111033',
        "city":      'Moscow',
        "country":   'Russia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '198758128',
    },
    'Limited Liability Company "Madan MSK Products"': {
        "vat_id":    '5030080547',
        "street":    'ул. Старокачаловская, д. 4, пом. 4/2',
        "postcode":  '117628',
        "city":      'Москва',
        "country":   'Russia',
        "email":     's.chernoburov@multiliga.ru',
        "phone":     '',
        "invoiceocean_id": '205584787',
    },
    'Limited Liability Company “VOXEN”': {
        "vat_id":    '193765993',
        "street":    'Timiryazeva 67, Office 513',
        "postcode":  '220035',
        "city":      'Minsk',
        "country":   'Belarus',
        "email":     'voxen.info@gmail.com',
        "phone":     '+375 33 377-00-00',
        "invoiceocean_id": '219982866',
    },
    'LKS Consult OÜ': {
        "vat_id":    'EE102154964',
        "street":    'Pärnu mnt 105',
        "postcode":  '11312',
        "city":      '',
        "country":   'Estonia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '160926474',
    },
    'LLC "Interopt"': {
        "vat_id":    '9718077310',
        "street":    'Beregovaya pass, h. 5A, b.1',
        "postcode":  '127282',
        "city":      'Moscow',
        "country":   'Russia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '198757610',
    },
    'LLC "Oazis"': {
        "vat_id":    '0274192135',
        "street":    'Gvardeiskaya street, house 57/1А, Liter A1, premises 172 (floor 1)',
        "postcode":  '450028',
        "city":      'Ufa',
        "country":   'Russia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '160882346',
    },
    'LLC «ГРОАЛЛС»': {
        "vat_id":    '193768600',
        "street":    'st. Timiryazeva, house 67-222',
        "postcode":  '220035',
        "city":      'Minsk',
        "country":   'Belarus',
        "email":     '',
        "phone":     '+375 29 630 20 08',
        "invoiceocean_id": '205578132',
    },
    'LLD "OPUS"': {
        "vat_id":    '7816307590',
        "street":    'Saint-Petersburg Sofiyskaya st. 4 litera A room 10H, office M-214/1',
        "postcode":  '192102',
        "city":      'Saint-Petersburg',
        "country":   'Russia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '164082905',
    },
    'Mahmoud Tlemsani': {
        "vat_id":    '',
        "street":    '',
        "postcode":  '',
        "city":      '',
        "country":   '',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '233191612',
    },
    'Olga Ingunza Gómez': {
        "vat_id":    '46222169N',
        "street":    'Rambla de Catalunya, 99, 1º 2ª',
        "postcode":  '08008',
        "city":      'Barcelona',
        "country":   '',
        "email":     'oingunza@gmail.com',
        "phone":     '+34 630828840',
        "invoiceocean_id": '210698267',
    },
    'Pascale Pouyet': {
        "vat_id":    '44937400800026',
        "street":    '208 av Du Pylone',
        "postcode":  '06600',
        "city":      'Antibes',
        "country":   'France',
        "email":     'pascalepouyet1@gmail.com',
        "phone":     '',
        "invoiceocean_id": '160947336',
    },
    'Pesco Supply B.V.': {
        "vat_id":    'NL 8105.77.926 B01',
        "street":    'Euclideslaan 101',
        "postcode":  '3584 BR',
        "city":      '',
        "country":   'Netherlands',
        "email":     'info@pescosupply.com',
        "phone":     '+31 30 266 73 84',
        "invoiceocean_id": '160947933',
    },
    'PILOT INTERNATIONAL SP. Z O.O.': {
        "vat_id":    '5242950541',
        "street":    'UL.STANIEWICKA 5',
        "postcode":  '03-310',
        "city":      'Warszawa',
        "country":   'Poland',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '160919372',
    },
    'SCI SACHA IMMOBILIER': {
        "vat_id":    '948317318',
        "street":    '208 avenue du Pylone',
        "postcode":  '06600',
        "city":      'Antibes',
        "country":   'France',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '160985288',
    },
    'Sergej Casovnikov': {
        "vat_id":    '',
        "street":    '',
        "postcode":  '',
        "city":      '',
        "country":   '',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '202234674',
    },
    'Sergej Chasovnikov': {
        "vat_id":    '',
        "street":    '',
        "postcode":  '',
        "city":      '',
        "country":   '',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '160988949',
    },
    'Stepanovski, Papakul and partners. Legal services LLC': {
        "vat_id":    '193588385',
        "street":    '16 Kuibyshev Street, 4th Floor',
        "postcode":  '220029',
        "city":      'Minsk',
        "country":   'Belarus',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '219986771',
    },
    'Tallinna notar Evelyn Roots': {
        "vat_id":    'EE100873988',
        "street":    'Rävala pst 3 / Kuke tn 2',
        "postcode":  '',
        "city":      'Tallinn',
        "country":   'Estonia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '206264156',
    },
    'Tenta Trade sp z o.o.': {
        "vat_id":    'PL5423456230',
        "street":    'Ludwika Zamenhofa 29',
        "postcode":  '15435',
        "city":      'Białystok',
        "country":   'Poland',
        "email":     'purchase@tentatrade.com',
        "phone":     '',
        "invoiceocean_id": '160865575',
    },
    'Triton LLC': {
        "vat_id":    '0100000798',
        "street":    '97/1a Adygeyskaya str.',
        "postcode":  '385100',
        "city":      'Тахтамукай',
        "country":   'Russia',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '195516368',
    },
    'UniStore Group LLC': {
        "vat_id":    '390528502',
        "street":    'Slobodskaya str.131',
        "postcode":  '220025',
        "city":      'MINSK',
        "country":   'Belarus',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '204015724',
    },
    'Vipcorp Trade OÜ': {
        "vat_id":    'EE102280045',
        "street":    'Pärnu mnt 105, 11312 Tallinn, Estonia',
        "postcode":  '11312',
        "city":      'Tallinn',
        "country":   'Estonia',
        "email":     'purchase@vipcorptrade.com',
        "phone":     '',
        "invoiceocean_id": '160940259',
    },
    'ООО "Абит" Системс': {
        "vat_id":    '192586650',
        "street":    'Ольшевского, дом 20, корп. 11, пом. 25 (офис 23)',
        "postcode":  '220073',
        "city":      'Минск',
        "country":   '',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '235712055',
    },
    'ООО "БелАкваБай"': {
        "vat_id":    '193728081',
        "street":    'Школьная, 68А, каб. 1',
        "postcode":  '212032',
        "city":      'Могилёвский район, д. Большая Боровка',
        "country":   'Belarus',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '203311588',
    },
    'ООО "Селеритас"': {
        "vat_id":    '193902397',
        "street":    'Пр-т Газеты Звязда, 16-29',
        "postcode":  '220117',
        "city":      '',
        "country":   '',
        "email":     '',
        "phone":     '',
        "invoiceocean_id": '210698971',
    },
}


# Seller profiles
SELLERS = {
    "FMCGOODS OÜ": {
        "name": "FMCGOODS OÜ",
        "tax_id": "EE102627019",
        "bank": "Zepter Bank",
        "account_eur": "BY13 ZEPT 3024 0025 2251 0978 0000",
        "account_rub": "BY94 ZEPT 3024 0025 2281 0643 0000",
        "currency_default": "EUR",
    },
    "TENTA TRADE SP. Z O.O.": {
        "name": "TENTA TRADE SP. Z O.O.",
        "tax_id": "PL5423456230",
        "bank": "PKO Bank Polski",
        "account_pln": "47 1020 1332 0000 1802 1389 3625",
        "account_eur": "52 1020 1332 0000 1602 1389 3633",
        "currency_default": "PLN",
    },
}
